### ISSUE TITLE
Several problems with the latest update of Wordpress

### ISSUE THREAD

**Issue by Potassium-40** [emandiev/woo-image-seo#2]
Hi, 
with the last update of WordPress (or maybe WooCommerce) the plugin does not work correctly anymore. 

Recently, the attributes of the images in the graphic arch are also changed, which is very annoying for SEO. 

Moreover, when you don't force the attributes, the alt text and title of all images on a page are identical (the numbers after to avoid duplicate are not added anymore).

**Comment by emandiev** [comment]
Hi,

Thanks for the feedback.
In order to find a solution, I would need more info about your environment.
- PHP version
- WordPress version
- WooCommerce version
- List of active plugins
- Theme name (or if custom theme, the template code)

If you prefer, you can contact me at emandiev@gmail.com and we can discuss this in private.

Thanks :)
